### ISSUE TITLE
Unable to install 

### ISSUE THREAD

**Issue by Diviyan-Kalainathan** [funkey/pylp#1]
Hi,
I got an error when installing the pylp package, even though all dependencies are filled : 

> python setup.py install
> running install
> running build
> running build_py
> Creating pycmc build directory in /home/diviyan/.lib/pylp/build_pylp
> mkdir: cannot create directory ‘/home/diviyan/.lib/pylp/build_pylp’: File exists
> Calling CMake for sources in /home/diviyan/.lib/pylp
> ./compile_wrapper.sh: line 14: cmake: command not found
> Creating target rename_pylp_lib
> make: *** No rule to make target 'rename_pylp_lib'.  Stop.
> target_dir: build/lib
> /home/diviyan/.lib/pylp/build_pylp/python/pylp
> Traceback (most recent call last):
>   File "setup.py", line 48, in <module>
>     cmdclass={'build_py' : cmake_lib}
>   File "/home/diviyan/miniconda2/lib/python2.7/distutils/core.py", line 151, in setup
>     dist.run_commands()
>   File "/home/diviyan/miniconda2/lib/python2.7/distutils/dist.py", line 953, in run_commands
>     self.run_command(cmd)
>   File "/home/diviyan/miniconda2/lib/python2.7/distutils/dist.py", line 972, in run_command
>     cmd_obj.run()
>   File "/home/diviyan/miniconda2/lib/python2.7/distutils/command/install.py", line 563, in run
>     self.run_command('build')
>   File "/home/diviyan/miniconda2/lib/python2.7/distutils/cmd.py", line 326, in run_command
>     self.distribution.run_command(command)
>   File "/home/diviyan/miniconda2/lib/python2.7/distutils/dist.py", line 972, in run_command
>     cmd_obj.run()
>   File "/home/diviyan/miniconda2/lib/python2.7/distutils/command/build.py", line 127, in run
>     self.run_command(cmd_name)
>   File "/home/diviyan/miniconda2/lib/python2.7/distutils/cmd.py", line 326, in run_command
>     self.distribution.run_command(command)
>   File "/home/diviyan/miniconda2/lib/python2.7/distutils/dist.py", line 972, in run_command
>     cmd_obj.run()
>   File "setup.py", line 35, in run
>     lib_file = [ lib_base + e for e in lib_extensions if os.path.isfile(lib_base + e) ][0]
> IndexError: list index out of range

Got any ideas on how to solve this ? 
Thanks a lot !

**Comment by funkey** [comment]
> ./compile_wrapper.sh: line 14: cmake: command not found

It seems you don't have `cmake` installed.

**Comment by Diviyan-Kalainathan** [comment]
Yes... 
Sorry I should read the error messages.
