### ISSUE TITLE
undefined symbol on import

### ISSUE THREAD

**Issue by marcusklaas** [funkey/pylp#2]
Hi!

I'm trying to run your pymfast code which uses pylp. On import of the library, I run into the following error:
```
Traceback (most recent call last):
  File "/home/marcusklaas/pymfast.py", line 3, in <module>
    import pylp
  File "/usr/lib/python2.7/site-packages/pylp/__init__.py", line 1, in <module>
    from .pylp import *
ImportError: /usr/lib/python2.7/site-packages/pylp/pylp.so: undefined symbol: _ZN5boost6python6detail11init_moduleER11PyModuleDefPFvvE
```
Is this a linking error? I have the boost development library installed.

The compilation and installation of pylp itself works flawlessly.

Grateful for any assistance on this!

**Comment by funkey** [comment]
I think this error indicates that pylp was built against a different python version than the one you use. Can you show the cmake output of your build?

By the way, there is also a conda package for pylp: https://anaconda.org/funkey/pylp

**Comment by marcusklaas** [comment]
Yup, that was totally it. I yearn for the day we no longer need double installs of python 2 and python 3!

Thanks!
